'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class WebProjectMechanics_SQLResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebProjectMechanics.WebProjectMechanics.SQLResources", GetType(WebProjectMechanics_SQLResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Company.CompanyID,  Company.CompanyName,  Company.GalleryFolder,  Company.SiteURL,  Company.SiteTitle,  Company.SiteTemplate,  Company.DefaultSiteTemplate,  Company.HomePageID,  Company.DefaultArticleID,  Company.ActiveFL,  Company.UseBreadCrumbURL,  Company.SiteCategoryTypeID,  Company.DefaultPaymentTerms,  Company.DefaultInvoiceDescription,  Company.City,  Company.StateOrProvince,  Company.PostalCode,  Company.Country,  Company.FromEmail, Company.SMTP, Company.Component, SiteCategoryType.SiteCatego [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetCompanyData() As String
            Get
                Return ResourceManager.GetString("GetCompanyData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT &apos;CompanySiteTypeParameter&apos; AS RecordSource, IIf(CompanySiteTypeParameter.CompanySiteTypeParameterID Is Null,0,10)+IIf(CompanySiteTypeParameter.SiteCategoryGroupID Is Null,0,1)+IIf(CompanySiteTypeParameter.SiteCategoryID Is Null,0,1)+IIf(CompanySiteTypeParameter.CompanyID Is Null,0,1) AS PrimarySort, CompanySiteTypeParameter.CompanyID, CompanySiteTypeParameter.SiteParameterTypeID, CompanySiteTypeParameter.SortOrder, CompanySiteTypeParameter.ParameterValue, iif(CompanySiteTypeParameter.SiteCategoryID i [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetCompanySiteTypeParameterList() As String
            Get
                Return ResourceManager.GetString("GetCompanySiteTypeParameterList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Contact.ContactID, Contact.LogonName, Contact.PrimaryContact,  Contact.GroupID,  Contact.LogonPassword,  Contact.Active,  Contact.EMail,  Contact.TemplatePrefix,  Company.CompanyID,  Company.CompanyName,  Company.GalleryFolder,  Company.SiteURL,  Company.SiteTitle,  Company.SiteTemplate, Company.DefaultArticleID, Company.HomePageID, Company.DefaultSiteTemplate, &apos;&apos; as RoleTitle, &apos;&apos; as RoleID, &apos;False&apos; as FilterMenu FROM Contact, Company  WHERE Contact.CompanyID=Company.CompanyID AND Contact.LogonName = [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetContactByLogonPassword() As String
            Get
                Return ResourceManager.GetString("GetContactByLogonPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Image.[ImageID], Image.[ImageName], Image.[ImageFileName], Image.[ImageThumbFileName], Image.[ImageDescription], Image.[ImageComment], Image.[ImageDate], Image.[Active], Image.[ModifiedDT], Image.[VersionNo], Image.[ContactID], Image.[CompanyID], Image.[Title], Image.[Medium], Image.[Size], Image.[Price], Image.[Color], Image.[Subject], Image.[Sold] FROM [Image] where [ImageID]={0} .
        '''</summary>
        Public Shared ReadOnly Property GetImageByImageID() As String
            Get
                Return ResourceManager.GetString("GetImageByImageID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Image.[ImageID], Image.[ImageName], Image.[ImageFileName], Image.[ImageThumbFileName], Image.[ImageDescription], Image.[ImageComment], Image.[ImageDate], Image.[Active], Image.[ModifiedDT], Image.[VersionNo], Image.[ContactID], Image.[CompanyID], Image.[Title], Image.[Medium], Image.[Size], Image.[Price], Image.[Color], Image.[Subject], Image.[Sold] FROM [Image] where [CompanyID]={0} .
        '''</summary>
        Public Shared ReadOnly Property GetImageList() As String
            Get
                Return ResourceManager.GetString("GetImageList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT LinkCategory.ID,  LinkCategory.Title,  LinkCategory.ParentID,  LinkCategory.Description,  LinkCategory.PageID,  0 AS CountOfID FROM LinkCategory .
        '''</summary>
        Public Shared ReadOnly Property GetLinkCategoryList() As String
            Get
                Return ResourceManager.GetString("GetLinkCategoryList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT PageAliasID, PageURL, TargetURL, AliasType from PageAlias where [CompanyID]={0} .
        '''</summary>
        Public Shared ReadOnly Property GetPageAliasList() As String
            Get
                Return ResourceManager.GetString("GetPageAliasList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT [Page].[PageID], [Page].[PageName], [Page].[PageDescription], [Page].[PageKeywords], [Page].[ImagesPerRow], [Page].[RowsPerPage], [PageImage].[PageImagePosition], [Image].[ImageID], [Image].[ImageName], [Image].[ImageFileName], [Image].[ImageThumbFileName], [Image].[ImageDescription], [Image].[ImageComment], [Image].[ImageDate], [Image].[ModifiedDT], [Image].[VersionNo], [Image].[ContactID], [Image].[title],  [Image].[medium],  [Image].[size] FROM [Page],[PageImage],[Image] WHERE [Page].[PageID] = [P [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetPageImageByCompanyID() As String
            Get
                Return ResourceManager.GetString("GetPageImageByCompanyID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT [Page].[PageID], [Page].[PageName], [Page].[PageDescription], [Page].[PageKeywords], [Page].[ImagesPerRow], [Page].[RowsPerPage], [Page].[PageFileName], [PageImage].[PageImagePosition], [Image].[ImageID], [Image].[ImageName], [Image].[ImageFileName], [Image].[ImageThumbFileName], [Image].[ImageDescription], [Image].[ImageComment], [Image].[ImageDate], [Image].[ModifiedDT], [Image].[VersionNo], [Image].[ContactID], [Image].[title],  [Image].[Price], [Image].[Color], [Image].[Subject], [Image].[Sold],  [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetPageImageByPageID() As String
            Get
                Return ResourceManager.GetString("GetPageImageByPageID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Link.ID,Link.LinkTypeCD, LinkCategory.Title as LinkCategoryTitle, Link.CategoryID, Link.PageID,Link.Title as LinkTitle, Link.Description, Link.URL, Link.DateAdd, Link.Ranks, Link.Views, Link.UserName, Link.UserID, Link.ASIN, Link.Ranks,  &apos;Link&apos; as LinkSource, &apos;&apos; as SiteCategoryTypeID, Link.SiteCategoryGroupID, Link.CompanyID FROM Link, LinkCategory where Link.CategoryID = LinkCategory.ID and ( Link.CompanyID ={0} or Link.CompanyID is null) union all SELECT SiteLink.ID,SiteLink.LinkTypeCD, LinkCategor [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetSiteCategoryLinks() As String
            Get
                Return ResourceManager.GetString("GetSiteCategoryLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT SiteCategoryGroup.[SiteCategoryGroupID], SiteCategoryGroup.[SiteCategoryGroupNM], SiteCategoryGroup.[SiteCategoryGroupDS], SiteCategoryGroup.[SiteCategoryGroupOrder]FROM SiteCategoryGroup;.
        '''</summary>
        Public Shared ReadOnly Property GetSiteGroupList() As String
            Get
                Return ResourceManager.GetString("GetSiteGroupList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Link.ID,Link.LinkTypeCD, LinkCategory.Title as LinkCategoryTitle, Link.CategoryID, Link.PageID,Link.Title as LinkTitle, Link.Description, Link.URL, Link.DateAdd, Link.Ranks, Link.Views, Link.UserName, Link.UserID, Link.ASIN, &apos;Link&apos; as LinkSource, &apos;&apos; as SiteCategoryTypeID, Link.SiteCategoryGroupID, Link.CompanyID FROM Link, LinkCategory where Link.CategoryID = LinkCategory.ID and ( Link.CompanyID ={0} or Link.CompanyID is null) ORDER BY Link.Ranks.
        '''</summary>
        Public Shared ReadOnly Property GetSiteLinks() As String
            Get
                Return ResourceManager.GetString("GetSiteLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Page.PageID, Article.Title AS PageName,  Article.Title AS PageTitle,  Article.Description,  Page.ParentPageID,  &apos;Article&apos; AS PageSource,  Page.PageKeywords,  IIf(pagetype.PageFileName Is Null,&quot;/default.aspx&quot;,pagetype.PageFileName) AS TransferURL, Page.PageFileName, Article.StartDT as ModifiedDT, Article.ArticleID, Article.Active, Page.PageOrder,  Page.SiteCategoryID, &apos; &apos; as SiteCategoryName, &apos; &apos; as SiteCategoryGroupName, &apos; &apos; as SiteCategoryGroupID, IIf(pagetype.PageTypeCD Is Null,&apos;Article&apos;,pagetype.P [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetSiteMapByGroup() As String
            Get
                Return ResourceManager.GetString("GetSiteMapByGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Page.PageID, Article.Title as PageName,  Article.Title as PageTitle,  Article.Description,  Page.ParentPageID,  &apos;Article&apos; AS PageSource,  Page.PageKeywords,  IIf(pagetype.PageFileName Is Null,&quot;/default.aspx&quot;,pagetype.PageFileName) AS TransferURL, Page.PageFileName, Article.StartDT as ModifiedDT, Article.ArticleID, Article.Active, Page.PageOrder,  Page.SiteCategoryID, &apos; &apos; as SiteCategoryName, &apos; &apos; as SiteCategoryGroupName, &apos; &apos; as SiteCategoryGroupID, IIf(pagetype.PageTypeCD Is Null,&apos;Article&apos;,pagetype.P [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetSiteMapByGroupAnon() As String
            Get
                Return ResourceManager.GetString("GetSiteMapByGroupAnon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CompanySiteTypeParameter.CompanySiteTypeParameterID,  CompanySiteTypeParameter.CompanyID,  CompanySiteTypeParameter.SiteParameterTypeID,  CompanySiteTypeParameter.SortOrder,  CompanySiteTypeParameter.ParameterValue,  CompanySiteTypeParameter.SiteCategoryGroupID,  CompanySiteTypeParameter.SiteCategoryID,  CompanySiteTypeParameter.ParameterValue,  CompanySiteTypeParameter.SiteCategoryTypeID, SiteParameterType.SiteParameterTypeID,  SiteParameterType.SiteParameterTypeNM,  SiteParameterType.SiteParameterT [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property GetSiteTypeParameter() As String
            Get
                Return ResourceManager.GetString("GetSiteTypeParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Image.[ImageID], Image.[ImageName], Image.[ImageFileName], Image.[ImageThumbFileName], Image.[ImageDescription], Image.[ImageComment], Image.[ImageDate], Image.[Active], Image.[ModifiedDT], Image.[VersionNo], Image.[ContactID], Image.[CompanyID], Image.[Title], Image.[Medium], Image.[Size], Image.[Price], Image.[Color], Image.[Subject], Image.[Sold] FROM [Image]  LEFT JOIN [PageImage] ON [Image].[ImageID] = [PageImage].[ImageID]  WHERE [PageImage].[PageID] Is Null and [CompanyID]={0} .
        '''</summary>
        Public Shared ReadOnly Property GetUnlinkedImageList() As String
            Get
                Return ResourceManager.GetString("GetUnlinkedImageList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT &apos;CompanySiteParameter&apos; AS RecordSource, iif(CompanySiteParameter.CompanySiteParameterID is null,0,10)+iif(CompanySiteParameter.SiteCategoryGroupID is null,0,1)+iif(CompanySiteParameter.PageID is null,0,1)+iif(CompanySiteParameter.CompanyID is null,0,1) as PrimarySort, CompanySiteParameter.CompanyID, CompanySiteParameter.SiteParameterTypeID, CompanySiteParameter.SortOrder, CompanySiteParameter.ParameterValue, CompanySiteParameter.PageID, CompanySiteParameter.SiteCategoryGroupID, &apos;&apos; AS SiteCategoryType [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property SELECTCompanySiteParameterASRecordSourceIi() As String
            Get
                Return ResourceManager.GetString("SELECTCompanySiteParameterASRecordSourceIi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT &apos;SiteParameterType&apos; AS RecordSource, 0 AS PrimarySort, Null AS CompanyID, Null AS SiteParameterTypeID, SiteParameterType.SiteParameterTypeOrder, SiteParameterType.SiteParameterTemplate, Null AS SiteCategoryID, Null AS SiteCategoryGroupID, Null AS SiteCategoryTypeID, SiteParameterType.SiteParameterTypeNM, SiteParameterType.SiteParameterTypeDS,0 as CompanySiteParameterID FROM(SiteParameterType) ORDER BY 2 desc,3 DESC, 7 DESC .
        '''</summary>
        Public Shared ReadOnly Property SELECTSiteParameterTypeASRecordSource0ASPr() As String
            Get
                Return ResourceManager.GetString("SELECTSiteParameterTypeASRecordSource0ASPr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [contact] SET [contact].[CreateDT]=&apos;{0}&apos;  WHERE [contact].[ContactID]={1} .
        '''</summary>
        Public Shared ReadOnly Property UpdateUserOptions() As String
            Get
                Return ResourceManager.GetString("UpdateUserOptions", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
